let episodes = [
    {"title": "Departure × And × Friends", "episode": 1},
    {"title": "Test × Of × Tests", "episode": 2},
    {"title": "Rivals × For × Survival", "episode": 3},
    {"title": "Hope × And × Ambition", "episode": 4},
    {"title": "Hisoka × Is × Sneaky", "episode": 5},
    {"title": "An × Unexpected × Task", "episode": 6},
    {"title": "Showdown × On × The Airship", "episode": 7},
    {"title": "Decision × By × Majority?", "episode": 8},
    {"title": "Beware × Of × Prisoners", "episode": 9},
    {"title": "Trick × To × The Trick", "episode": 10},
    {"title": "Trouble × With × The Gamble", "episode": 11},
    {"title": "Last Test × Of × Resolve!", "episode": 12},
    {"title": "Letter × From × Gon", "episode": 13},
    {"title": "Hit × The × Target", "episode": 14},
    {"title": "Explosion × Of × Deception", "episode": 15},
    {"title": "Defeat × And × Disgrace", "episode": 16},
    {"title": "Trap × In The × Hole", "episode": 17},
    {"title": "Big × Time × Interview", "episode": 18},
    {"title": "Can't Win × But × Can't Lose", "episode": 19},
    {"title": "Baffling Turn × Of × Events", "episode": 20},
    {"title": "Some × Brother × Trouble", "episode": 21},
    {"title": "A × Dangerous × Watchdog", "episode": 22},
    {"title": "The × Guard's × Duty", "episode": 23},
    {"title": "The × Zoldyck × Family", "episode": 24},
    {"title": "Can't See × If × You're Blind", "episode": 25},
    {"title": "Then × And × After", "episode": 26},
    {"title": "Arrival × At × The Arena", "episode": 27},
    {"title": "Nen × And × Nen", "episode": 28},
    {"title": "Awakening × And × Potential", "episode": 29},
    {"title": "Fierce × And × Ferocious", "episode": 30},
    {"title": "Destiny × And × Tenacity", "episode": 31},
    {"title": "A × Surprising × Win", "episode": 32},
    {"title": "An × Empty × Threat", "episode": 33},
    {"title": "Power × To × Avenge", "episode": 34},
    {"title": "The × True × Pass", "episode": 35},
    {"title": "A Big Debt × And × A Small Kick", "episode": 36},
    {"title": "Ging × And × Gon", "episode": 37},
    {"title": "Reply × From × Dad", "episode": 38},
    {"title": "Wish × And × Promise", "episode": 39},
    {"title": "Nen × Users × Unite?", "episode": 40},
    {"title": "Gathering × Of × Heroes", "episode": 41},
    {"title": "Defend × And × Attack", "episode": 42},
    {"title": "A × Shocking × Tragedy", "episode": 43},
    {"title": "Buildup × To A × Fierce Battle", "episode": 44},
    {"title": "Restraint × And × Vow", "episode": 45},
    {"title": "Chasing × And × Waiting", "episode": 46},
    {"title": "Condition × And × Condition", "episode": 47},
    {"title": "Very × Sharp × Eye", "episode": 48},
    {"title": "Pursuit × And × Analysis", "episode": 49},
    {"title": "Ally × And × Sword", "episode": 50},
    {"title": "A × Brutal × Battlefield", "episode": 51},
    {"title": "Assault × And × Impact", "episode": 52},
    {"title": "Fake × And × Psyche", "episode": 53},
    {"title": "Fortunes × Aren't × Right?", "episode": 54},
    {"title": "Allies × And × Lies", "episode": 55},
    {"title": "Beloved × And × Beleaguered", "episode": 56},
    {"title": "Initiative × And × Law", "episode": 57},
    {"title": "Time × To × Retreat", "episode": 58},
    {"title": "Bid × And × Haste", "episode": 59},
    {"title": "End × And × Beginning", "episode": 60},
    {"title": "Invitation × And × Friend", "episode": 61},
    {"title": "Reality? × And × Raw", "episode": 62},
    {"title": "A × Hard × Master?", "episode": 63},
    {"title": "Strengthen × And × Threaten", "episode": 64},
    {"title": "Evil Fist × And × Rock-Paper-Scissors", "episode": 65},
    {"title": "Strategy × And × Scheme", "episode": 66},
    {"title": "15 × 15", "episode": 67},
    {"title": "Pirates × And × Guesses", "episode": 68},
    {"title": "A × Heated × Showdown", "episode": 69},
    {"title": "Guts × And × Courage", "episode": 70},
    {"title": "Bargain × And × Deal", "episode": 71},
    {"title": "Chase × And × Chance", "episode": 72},
    {"title": "Insanity × And × Sanity", "episode": 73},
    {"title": "Victor × And × Loser", "episode": 74},
    {"title": "Ging's Friends × And × True Friends", "episode": 75},
    {"title": "Reunion × And × Understanding", "episode": 76},
    {"title": "Unease × And × Sighting", "episode": 77},
    {"title": "Very × Rapid × Reproduction", "episode": 78},
    {"title": "No × Good × NGL", "episode": 79},
    {"title": "Evil × And × Terrible", "episode": 80},
    {"title": "The × Fight × Begins", "episode": 81},
    {"title": "Kite × And × Slots", "episode": 82},
    {"title": "Inspiration × To × Evolve", "episode": 83},
    {"title": "A × Fated × Awakening", "episode": 84},
    {"title": "Light × And × Darkness", "episode": 85},
    {"title": "Promise × And × Reunion", "episode": 86},
    {"title": "Duel × And × Escape", "episode": 87},
    {"title": "Rock-Paper-Scissors × And × Weakness", "episode": 88},
    {"title": "Compassion × And × Strength", "episode": 89},
    {"title": "Slow × And × Cursed", "episode": 90},
    {"title": "The Strong × And × The Weak", "episode": 91},
    {"title": "One Wish × And × Two Promises", "episode": 92},
    {"title": "Date × With × Palm", "episode": 93},
    {"title": "Friend × And × Journey", "episode": 94},
    {"title": "Grudge × And × Dread", "episode": 95},
    {"title": "A × Lawless × Home", "episode": 96},
    {"title": "Carnage × And × Devastation", "episode": 97},
    {"title": "Infiltration × And × Selection", "episode": 98},
    {"title": "Combination × And × Evolution", "episode": 99},
    {"title": "Tracking × And × Pursuit", "episode": 100},
    {"title": "Ikalgo × And × Lightning", "episode": 101},
    {"title": "Power × And × Games", "episode": 102},
    {"title": "Check × And × Mate", "episode": 103},
    {"title": "Doubt × And × Hesitation", "episode": 104},
    {"title": "Resolve × And × Awakening", "episode": 105},
    {"title": "Knov × And × Morel", "episode": 106},
    {"title": "Return × And × Retire", "episode": 107},
    {"title": "Gungi × Of × Komugi", "episode": 108},
    {"title": "Taking Stock × And × Taking Action", "episode": 109},
    {"title": "Confusion × And × Expectation", "episode": 110},
    {"title": "Charge × And × Invade", "episode": 111},
    {"title": "Monster × And × Monster", "episode": 112},
    {"title": "An × Indebted × Insect", "episode": 113},
    {"title": "Divide × And × Conquer", "episode": 114},
    {"title": "Duty × And × Question", "episode": 115},
    {"title": "Revenge × And × Recovery", "episode": 116},
    {"title": "Insult × And × Payback", "episode": 117},
    {"title": "A × False × Rage", "episode": 118},
    {"title": "Strong × Or × Weak", "episode": 119},
    {"title": "Fake × And × Real", "episode": 120},
    {"title": "Defeat × And × Dignity", "episode": 121},
    {"title": "Pose × And × Name", "episode": 122},
    {"title": "Centipede × And × Memory", "episode": 123},
    {"title": "Breakdown × And × Awakening", "episode": 124},
    {"title": "Great Power × And × Ultimate Power", "episode": 125},
    {"title": "Zero × And × Rose", "episode": 126},
    {"title": "Hostility × And × Determination", "episode": 127},
    {"title": "Unparalleled Joy × And × Unconditional Love", "episode": 128},
    {"title": "Formidable Enemy × And × Clear Objective", "episode": 129},
    {"title": "Magic × To × Destroy", "episode": 130},
    {"title": "Anger × And × Light", "episode": 131},
    {"title": "Flash × And × Start", "episode": 132},
    {"title": "Deadline × To × Live", "episode": 133},
    {"title": "The Word × Is × You", "episode": 134},
    {"title": "This Day × And × This Moment", "episode": 135},
    {"title": "Homecoming × And × Real Name", "episode": 136},
    {"title": "Debate × Among × Zodiacs", "episode": 137},
    {"title": "Request × And × Wish", "episode": 138},
    {"title": "Alluka × And × Something", "episode": 139},
    {"title": "Join Battle × And × Open Battle", "episode": 140},
    {"title": "Magician × And × Butler", "episode": 141},
    {"title": "Needles × And × Debt", "episode": 142},
    {"title": "Sin × And × Claw", "episode": 143},
    {"title": "Approval × And × Coalition", "episode": 144},
    {"title": "Defeat × And × Reunion", "episode": 145},
    {"title": "Chairman × And × Release", "episode": 146},
    {"title": "Salvation × And × Future", "episode": 147},
    {"title": "Past × And × Future", "episode": 148}
];


const getRandomEpisode = () => {
    const episode = episodes[Math.floor(Math.random() * episodes.length)];
    let title = episode.title.replace(" × And × ", " × ");
    const split = title.split(" × ");
    episode.episode = `${episode.episode}`;

    if (split.length === 2) {
        return {
            top: split[0],
            bottom: split[1],
            left: "episode",
            right: episode.episode
        };
    }
    if (split[0].trim().length <= 3) {
        split[0] = split[0].trim() +" " + split[1].trim();
        split[0] = split[0].trim();
        split.splice(1, 1);
        return {
            top: split[0],
            bottom: split[1],
            left: "episode",
            right: episode.episode
        };
    }
    return {
        top: split[0],
        left: split[1],
        bottom: split[2],
    };
};


export { getRandomEpisode };